【question】调整注册中心地址为公共参数
sermant-io/Sermant pull request #1046
Opened 2022-12-19 03:35 UTC by chengyouling

【修复issue】#1043

【修改内容】调整注册中心地址为公共参数

【用例描述】不需要
【自测情况】1、本地静态检查清理情况；

【影响范围】用户通过sermant-injector设置注册中心地址

2022-12-19 06:57 UTC, provenceee approved these changes, later dismissed

2022-12-20 07:09 UTC, justforstudy-A commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +        return new ArrayList<>(Arrays.asList(address.split(",")));
这里做下trim吧，有可能会有空格

2022-12-20 07:46 UTC, chengyouling commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +        return new ArrayList<>(Arrays.asList(address.split(",")));
已调整

2022-12-20 08:19 UTC, provenceee commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +        if (StringUtils.isBlank(address) || StringUtils.isBlank(address.trim())) {
StringUtils.isBlank本身就会判断是否纯空格，所以判断address.trim()是无意义的

2022-12-20 08:20 UTC, robotLJW requested changes

2022-12-20 08:20 UTC, robotLJW commented on docs/user-guide/registry/document-zh.md
> +  address: http://127.0.0.1:30100 #注册服务地址，多个注册中心地址使用逗号分隔；nacos：127.0.0.1:8848
这个格式和下面yaml格式保持一样，注册服务地址，service_comb：http://localhost:30100；nacos：127.0.0.1:8848

2022-12-20 09:06 UTC, robotLJW commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +import java.util.Arrays;
Checkstyle 问题记得修改一下  Unused import - java.util.Arrays.

2022-12-20 09:09 UTC, robotLJW commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +            if (item.length() > 0 && item.trim().length() > 0) {
这个是不是多判断了，只要item.trim().length() 就行了

2022-12-20 09:15 UTC, chengyouling commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +        if (StringUtils.isBlank(address) || StringUtils.isBlank(address.trim())) {
已调整

2022-12-20 09:16 UTC, justforstudy-A commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +            if (item.length() > 0 && item.trim().length() > 0) {
使用上面的StringUtils.isBlank就可以了

2022-12-20 10:12 UTC, chengyouling commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +            if (item.length() > 0 && item.trim().length() > 0) {
已调整

2022-12-20 10:12 UTC, chengyouling commented on sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
> +import java.util.Arrays;
已调整

2022-12-20 10:12 UTC, chengyouling commented on docs/user-guide/registry/document-zh.md
> +  address: http://127.0.0.1:30100 #注册服务地址，多个注册中心地址使用逗号分隔；nacos：127.0.0.1:8848
已调整

2022-12-20 10:32 UTC, justforstudy-A approved these changes

2022-12-20 10:33 UTC, provenceee approved these changes

2022-12-20 11:06 UTC, robotLJW approved these changes

2022-12-20 11:06 UTC, merged