流量标签透传特性：支持rocketMQ4.8+，支持webServlet3.0+
sermant-io/Sermant pull request #1253
Opened 2023-07-21 03:26 UTC by TangLeDaily

2023-7-21 11:05:56 TangLe

【修复issue】#1244

【修改内容】

1. 新增rocketMQ4.8+的消费者和生产者流量标签透传
2. 新增webServlet3.0+服务端的流量标签透传

【用例描述】后续补充测试用例

【自测情况】1、本地静态检查通过；2、本地自测通过

【影响范围】无

2023-07-21 07:43 UTC, hanbingleixue requested changes

2023-07-21 07:43 UTC, hanbingleixue commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/HttpServletDeclarer.java
> +        return ClassMatcher.nameEquals(ENHANCE_CLASS);
HttpServlet是一个抽象类，不建议用nameEquals，建议用isExtendedFrom

2023-07-21 07:43 UTC, hanbingleixue commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/HttpServletInterceptor.java
> +                if (!CollectionUtils.isEmpty(values)) {
建议先通过hasMoreElements()判断valuesEnumeration 是否为空，不为空时再执行Collections.list(valuesEnumeration)。

2023-07-21 07:43 UTC, hanbingleixue commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +        if (!tagTransmissionConfig.isEnabled()) {
建议先判断tagTransmissionConfig.isEnabled()。在进行stackTraceElements循环判断

2023-07-21 07:43 UTC, hanbingleixue commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +                tag.put(key, null);
value 为null是为什么也要放到tag里面

2023-07-21 08:11 UTC, TangLeDaily commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +                tag.put(key, null);
这一步之后调用的是Map.putAll(Map)。因为可能存在上条消息，上条消息的tag包含这个key-value。当运行到当前消息，如果此key-value为空，会不更改的话，putAll会保留上条消息的tag的key-value

2023-07-21 08:34 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/pom.xml
> +            <version>3.0.1</version>
version都放到properties里面

2023-07-21 08:47 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/HttpServletInterceptor.java
> +        MARK.remove();
onThrow也需要remove

2023-07-21 08:56 UTC, hanbingleixue commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/HttpServletInterceptor.java
> +                    if (!CollectionUtils.isEmpty(values)) {
这个判断应该不需要了。 valuesEnumeration.hasMoreElements()为true时，!CollectionUtils.isEmpty(values)也为true

2023-07-21 09:01 UTC, hanbingleixue submitted a review, later dismissed

2023-07-21 09:15 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +                if (i == stackTraceElements.length - 1 || stackTraceElements[i + 1].getClassName()
这里最好改成卫语句

2023-07-21 09:15 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProviderInterceptor.java
> +public class RocketmqProviderInterceptor extends AbstractInterceptor {
Provider命名改成Producer

2023-07-21 09:15 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/RocketmqProviderDeclarer.java
> +public class RocketmqProviderDeclarer extends AbstractPluginDeclarer {
Provider命名改成Producer

2023-07-21 09:15 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProviderInterceptor.java
> +        } else if (newProperties.length() > 0) {
避免if嵌套，用卫语句

2023-07-21 11:56 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/RocketmqProducerDeclarer.java
> +    private static final Integer PARAM_INDEX = 12;
改成int

2023-07-21 12:08 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +        StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
不要使用调用栈作为判断条件，如果某个版本的调用关系发生了变化，那么调用栈就会发生改变，另外aop/agent也可能会改变调用栈

2023-07-21 12:19 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +    public static final Integer ARGUMENT_INDEX = 3;
优先使用基础数据类型，类中的常量建议为私有，如果需要为公共常量，则提取到常量类中

2023-07-21 12:19 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +    public static final Character LINK_MARK = 1;
优先使用基础数据类型，类中的常量建议为私有，如果需要为公共常量，则提取到常量类中

2023-07-21 12:19 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +    public static final Character SPLIT_MARK = 2;
优先使用基础数据类型，类中的常量建议为私有，如果需要为公共常量，则提取到常量类中

2023-07-21 12:19 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/HttpServletDeclarer.java
> +    public static final String ENHANCE_CLASS = "javax.servlet.http.HttpServlet";
改为私有常量

2023-07-21 12:20 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/RocketmqConsumerDeclarer.java
> +    public static final String ENHANCE_CLASS = "org.apache.rocketmq.common.message.Message";
改为私有常量，如果需要为公有常量，建议提取到常量类中

2023-07-21 12:20 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/declarers/RocketmqProducerDeclarer.java
> +    public static final String ENHANCE_CLASS = "org.apache.rocketmq.client.impl.MQClientAPIImpl";
改为私有常量，如果需要为公有常量，建议提取到常量类中

2023-07-21 12:21 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +    public static final String ROCKETMQ_SELECT_CLASSNAME = "org.apache.rocketmq.common.message.Message";
改为私有常量，如果需要为公有常量，建议提取到常量类中

2023-07-21 12:21 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +    public static final String ROCKETMQ_FILER_PREFIX = "org.apache.rocketmq";
改为私有常量，如果需要为公有常量，建议提取到常量类中

2023-07-21 12:22 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +    public Map<String, List<String>> getTagFromMessage(Message message) {
或许可以改为私有方法？

2023-07-21 12:23 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +    public String insertTags2Properties(String oldProperties, TrafficTag trafficTag) {
或许可以改为私有方法？

2023-07-21 12:23 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +     * 将流量标签插入到properties字符串中 原始properties的格式形如：key1value1key2value2，其中[SOH]为ASCII=1的符号，[STX]为ASCII=2的符号
注释乱码了，需要改成utf8编码？

2023-07-22 09:33 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +            if (!stackTraceElements[i].getClassName().equals(ROCKETMQ_SELECT_CLASSNAME)) {
常量写左边

2023-07-22 09:34 UTC, provenceee commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +            if (i == stackTraceElements.length - 1 || stackTraceElements[i + 1].getClassName()
stackTraceElements.length - 1 为一个确定的值，不需要在for循环中计算

2023-07-24 01:06 UTC, TangLeDaily commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqConsumerInterceptor.java
> +        StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
这里因为getbody方法多次被调用，rocketMQ的生产者和消费者SDK自己会多次调用这个方法，导致无法精准定位用户调用的getBody方法，会议讨论后决定暂时先使用调用栈的形式

2023-07-24 02:59 UTC, lilai23 commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/RocketmqProducerInterceptor.java
> +        }
if newProperties长度为0 -> return oldProperties.tostring()
if oldProperties长度为0 -> return newProperties.deleteCharAt(newProperties.length() - 1);
return  newProperties.append(oldProperties).tostring;
这样避免嵌套 逻辑更清晰

2023-07-24 11:25 UTC, provenceee approved these changes, later dismissed

2023-07-25 01:34 UTC, luanwenfei-venus approved these changes, later dismissed

2023-07-25 01:34 UTC, luanwenfei-venus commented on sermant-plugins/sermant-tag-transmission/tag-transmission-plugin/src/main/java/com/huaweicloud/sermant/tag/transmission/interceptors/HttpServletInterceptor.java
> +    private static final ThreadLocal<Boolean> MARK = new ThreadLocal<>();
MARK命名不能表达其真实含义，也没有注释，建议修改

2023-07-25 06:26 UTC, luanwenfei-venus approved these changes, later dismissed

2023-07-25 08:13 UTC, lilai23 approved these changes, later dismissed

2023-07-25 08:58 UTC, lilai23 approved these changes

2023-07-25 09:26 UTC, luanwenfei-venus approved these changes

2023-07-25 09:26 UTC, merged