日志打印模板增加文件，类，方法信息
sermant-io/Sermant pull request #586
Opened 2022-07-19 12:37 UTC by xuezechao1

【issue号/问题单号/需求单号】#585

【修改内容】日志打印模板增加文件，类，方法信息

【用例描述】不需用例

【自测情况】本地静态检查通过，编译处包通过，demo插件应用运行通过

【影响范围】用户可以通过查看日志信息更好的进行定位

2022-07-19 14:31 UTC, robotLJW requested changes

2022-07-19 14:31 UTC, robotLJW commented on sermant-agentcore/sermant-agentcore-config/config/logback.xml
> +                ${pattern}
这个名词改成logPattern或者log-pattern？这边是什么样的命名规则？建议修改一下名字

2022-07-20 01:07 UTC, xuezechao1 commented on sermant-agentcore/sermant-agentcore-config/config/logback.xml
> +                ${pattern}
已修改成 log.pattern

2022-07-20 01:31 UTC, justforstudy-A approved these changes

2022-07-20 01:48 UTC, robotLJW approved these changes

2022-07-20 01:48 UTC, merged